# Site settings
title: Sticky Sidebar ⬆⬇
tag_text: Sticky Sidebar 😎
description: 

# Build settings
markdown: kramdown
exclude: ["README.md", "node_modules"]
sass:
  style: compressed
repository: blixhavn/sticky-sidebar.git
theme: jekyll-theme-cayman
